### ISSUE TITLE
Incorrect arrangement of domains in Uniprot reference file

### ISSUE THREAD

**Issue by alekhyaa2** [NaegleLab/CoDIAC#52]
**Is your feature request related to a problem? Please describe.**
The uniprot reference file created includes Interpro domains column. The domains extracted from interpro are not in the right order based on their domain ranges. 
For example, GRAP2 - Interpro domains are SH3_domain:IPR001452:1:56;SH3_domain:IPR001452:271:330;SH2:IPR000980:56:149. The sh2 domain should be in between the two sh3 domains but the order is rearranged. Similarly found this issue with VAV1. 
This is important for downstream analysis that uses this reference file for feature generation.

**Comment by knaegle** [comment]
Fixed this, it is done at the time of return from InterPro module, these now come back in the order by start site.
